/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dukofarms;

import java.util.List;

/**
 *
 * @author DEll
 */
public class customers extends javax.swing.JPanel {

    /**
     * Creates new form customers
     */
    public customers() {
        initComponents();
        this.setBackground(new java.awt.Color(150,100,50,75));
        searchByNameRadio.setOpaque(false);
        searchByCnicRadio.setOpaque(false);
        Clear.setOpaque(false);
        Search.setOpaque(false);
        jTable3.setOpaque(false);
        searchByName.setEnabled(false);
        searchByCnicRadio.setEnabled(false);
        jtablemodelCustomers t = new jtablemodelCustomers(DukoFarms.getIsntance().getAllCustomers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchByNameRadio = new javax.swing.JRadioButton();
        searchByName = new javax.swing.JTextField();
        searchByCnicRadio = new javax.swing.JRadioButton();
        searchByCnic = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Search = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(520, 410));

        searchByNameRadio.setBackground(new java.awt.Color(255, 255, 255));
        searchByNameRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchByNameRadio.setForeground(new java.awt.Color(255, 255, 255));
        searchByNameRadio.setText("Search by name");
        searchByNameRadio.setToolTipText("");
        searchByNameRadio.setBorder(null);
        searchByNameRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchByNameRadioItemStateChanged(evt);
            }
        });
        searchByNameRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByNameRadioActionPerformed(evt);
            }
        });

        searchByName.setBackground(new java.awt.Color(150, 100, 50));
        searchByName.setForeground(new java.awt.Color(255, 255, 255));
        searchByName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchByCnicRadio.setBackground(new java.awt.Color(255, 255, 255));
        searchByCnicRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchByCnicRadio.setForeground(new java.awt.Color(255, 255, 255));
        searchByCnicRadio.setText("Search by CNIC");
        searchByCnicRadio.setBorder(null);
        searchByCnicRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchByCnicRadioItemStateChanged(evt);
            }
        });

        searchByCnic.setBackground(new java.awt.Color(150, 100, 50));
        searchByCnic.setForeground(new java.awt.Color(255, 255, 255));
        searchByCnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchByCnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCnicActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(150, 100, 50));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText(" Clear filters ");
        Clear.setBorder(null);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(150, 100, 50));
        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_control_point_black_24dp.png"))); // NOI18N
        add.setText("Add new customers");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jTable3.setBackground(new java.awt.Color(150, 100, 50));
        jTable3.setForeground(new java.awt.Color(150, 100, 50));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Contact", "Milk Received", "View", "Update", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        Search.setBackground(new java.awt.Color(150, 100, 50));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2021-05-23 at 9.09.11 AM.jpeg"))); // NOI18N
        Search.setBorder(null);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByNameRadio)
                            .addComponent(searchByCnicRadio))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Clear)
                                .addGap(124, 124, 124)
                                .addComponent(Search))
                            .addComponent(searchByName)
                            .addComponent(searchByCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByNameRadio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchByCnicRadio)
                            .addComponent(searchByCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Search))
                    .addComponent(Clear))
                .addGap(39, 39, 39)
                .addComponent(add)
                .addGap(76, 76, 76)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchByNameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByNameRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByNameRadioActionPerformed

    private void searchByCnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByCnicActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        addCustomer ac = new addCustomer();
        ac.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void searchByNameRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchByNameRadioItemStateChanged
        // TODO add your handling code here:
        if(searchByNameRadio.isSelected())
        {
            searchByCnic.setText("");
            searchByName.setEnabled(true);
            searchByCnic.setEnabled(false);
        }
    }//GEN-LAST:event_searchByNameRadioItemStateChanged

    private void searchByCnicRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchByCnicRadioItemStateChanged
        // TODO add your handling code here:
        if(searchByCnicRadio.isSelected())
        {    
            searchByName.setText("");
            searchByName.setEnabled(false);
            searchByCnic.setEnabled(true);
        }
    }//GEN-LAST:event_searchByCnicRadioItemStateChanged

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        searchByCnic.setEnabled(false);
        searchByName.setEnabled(false);
        searchByCnicRadio.setSelected(false);
        searchByNameRadio.setSelected(false);
        
        jTable3.setModel(new jtablemodelCustomers(DukoFarms.getIsntance().getAllCustomers()));
    }//GEN-LAST:event_ClearActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        List<Customer> searched = null;
        if(searchByNameRadio.isSelected())
        {
            searched = DukoFarms.getIsntance().searchBasedOnName(searchByName.getText());
        }
        else if(searchByCnicRadio.isSelected())
        {
            searched = DukoFarms.getIsntance().searchBasedOnCNIC(searchByCnic.getText());
        }
        jTable3.setModel(new jtablemodelCustomers(DukoFarms.getIsntance().getAllCustomers()));
    }//GEN-LAST:event_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Search;
    private javax.swing.JButton add;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField searchByCnic;
    private javax.swing.JRadioButton searchByCnicRadio;
    private javax.swing.JTextField searchByName;
    private javax.swing.JRadioButton searchByNameRadio;
    // End of variables declaration//GEN-END:variables
}
